[package]
name = "state_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary-heap-plus = "0.5.0"
crossbeam-channel = "0.5.6"
eframe = "0.19.0"
parking_lot = "0.12.1"
rfd = "0.10.0"
rodio = "0.16.0"
